table ip mytable {
	chain chain_prerout {
		type nat hook prerouting priority filter; policy accept;
		iif "enp2s0" tcp dport 80 dnat to 192.168.89.2
	}

	chain chain_postrout {
		type nat hook postrouting priority filter; policy accept;
		ip saddr 192.168.89.0/24 oif "enp2s0" snat to 192.168.231.1
		ip saddr 172.16.44.2 oif "enp2s0" snat to 192.168.231.1
	}

	chain chain_output {
		type filter hook output priority filter; policy accept;
		icmp type echo-request accept
		icmp type echo-reply ip daddr 172.16.44.2 accept
		tcp sport 22 ip daddr 172.16.44.2 accept
		ip daddr 192.168.89.0/24 icmp type echo-reply accept
		oif "enp2s0" tcp dport 80 accept
		oif "enp26s0" tcp dport 80 accept
		tcp dport 1514 accept
		tcp dport 1515 accept
		drop
	}

	chain chain_input {
		type filter hook input priority filter; policy accept;
		icmp type echo-reply accept
		icmp type echo-request ip saddr 172.16.44.2 accept
		tcp dport 22 ip saddr 172.16.44.2 accept
		ip saddr 192.168.89.0/24 icmp type echo-request accept
		iif "enp2s0" tcp sport 80 ct state established,related accept
		iif "enp26s0" tcp sport 80 ct state established,related accept
		tcp sport 1514 ct state established,related accept
		tcp sport 1515 ct state established,related accept
		drop
	}

	chain chain_forward {
		type filter hook forward priority filter; policy accept;
		icmp type echo-request oif "enp2s0" accept
		iif "enp2s0" icmp type echo-reply ct state established,related accept
		tcp dport 80 oif "enp2s0" accept
		tcp sport 80 iif "enp2s0" ct state established,related accept
		iif "enp2s0" tcp dport 80 ip daddr 192.168.89.0/24 accept
		oif "enp2s0" tcp sport 80 ip daddr 192.168.231.0/24 accept
		iif "enp3s0" tcp dport 80 ip saddr 172.16.44.2 ip daddr 192.168.89.0/24 accept
		oif "enp3s0" tcp sport 80 ip daddr 172.16.44.2 ip saddr 192.168.89.0/24 ct state established,related accept
		oif "enp3s0" tcp sport 22 ip daddr 172.16.44.2 ip saddr 192.168.89.0/24 ct state established,related accept
		iif "enp3s0" tcp dport 22 ip saddr 172.16.44.2 ip daddr 192.168.89.0/24 accept
		oif "enp3s0" icmp type echo-reply ip daddr 172.16.44.2 ip saddr 192.168.89.0/24 ct state established,related accept
		iif "enp3s0" icmp type echo-request ip saddr 172.16.44.2 ip daddr 192.168.89.0/24 accept
		jump log_chain_forward
		drop
	}

	chain log_chain_forward {
		iif "enp2s0" icmp type echo-reply ct state invalid,new,untracked log prefix "CT-ERR_FROM-EXTERNAL_ICMP-REP_"
		iif "enp2s0" tcp sport 80 ct state invalid,new,untracked log prefix "CT-ERR_FROM-EXTERNAL_HTTP-REP_"
		oif "enp3s0" tcp sport 80 ip daddr 172.16.44.2 ip saddr 192.168.89.0/24 ct state invalid,new,untracked log prefix "CT-ERR_FROM-DMZ-TO-ADMIN_HTTP-REP_"
		oif "enp3s0" tcp sport 22 ip daddr 172.16.44.2 ip saddr 192.168.89.0/24 ct state invalid,new,untracked log prefix "CT-ERR_FROM-DMZ-TO-ADMIN_SSH-REP_"
		oif "enp3s0" icmp type echo-reply ip daddr 172.16.44.2 ip saddr 192.168.89.0/24 ct state invalid,new,untracked log prefix "CT-ERR_FROM-DMZ-TO-ADMIN_ICMP-REP_"
		iif "enp2s0" tcp dport 80 ip daddr 172.16.44.0/24 log prefix "DENY_FROM-EXTERNAL-TO-ADMIN_HTTP-REQ_"
		iif "enp26s0" tcp dport 80 ip daddr 172.16.44.0/24 log prefix "DENY_FROM-DMZ-TO-ADMIN_HTTP-REQ_"
		iif "enp2s0" tcp dport 22 ip daddr 172.16.44.0/24 log prefix "DENY_FROM-EXTERNAL-TO-ADMIN_SSH-REQ_"
		iif "enp2s0" tcp dport 22 ip daddr 192.168.89.0/24 log prefix "DENY_FROM-EXTERNAL-TO-DMZ_SSH-REQ_"
		iif "enp26s0" tcp dport 22 ip daddr 172.16.44.0/24 log prefix "DENY_FROM-DMZ-TO-ADMIN_SSH-REQ_"
		iif "enp2s0" icmp type echo-request ip daddr 172.16.44.0/24 log prefix "DENY_FROM-EXTERNAL-TO-ADMIN_ICMP-REQ_"
		iif "enp2s0" icmp type echo-request ip daddr 192.168.89.0/24 log prefix "DENY_FROM-EXTERNAL-TO-DMZ_ICMP-REQ_"
		iif "enp26s0" icmp type echo-request ip daddr 172.16.44.0/24 log prefix "DENY_FROM-DMZ-TO-ADMIN_ICMP-REQ_"
	}
}
